IAX_PROTO_VERSION = 2
IAX_MAX_CALLS = 2048
IAX_MAX_CALLS = 32768
IAX_FLAG_FULL = 0x8000
IAX_FLAG_RETRANS = 0x8000
IAX_FLAG_SC_LOG = 0x80
IAX_MAX_SHIFT = 0x1F
IAX_WINDOW = 64
IAX_COMMAND_NEW = 1
IAX_COMMAND_PING = 2
IAX_COMMAND_PONG = 3
IAX_COMMAND_ACK = 4
IAX_COMMAND_HANGUP = 5
IAX_COMMAND_REJECT = 6
IAX_COMMAND_ACCEPT = 7
IAX_COMMAND_AUTHREQ = 8
IAX_COMMAND_AUTHREP = 9
IAX_COMMAND_INVAL = 10
IAX_COMMAND_LAGRQ = 11
IAX_COMMAND_LAGRP = 12
IAX_COMMAND_REGREQ = 13 # Registration request
IAX_COMMAND_REGAUTH = 14 # Registration authentication required
IAX_COMMAND_REGACK = 15 # Registration accepted
IAX_COMMAND_REGREJ = 16 # Registration rejected
IAX_COMMAND_REGREL = 17 # Force release of registration
IAX_COMMAND_VNAK = 18 # If we receive voice before valid first voice frame, send this
IAX_COMMAND_DPREQ = 19 # Request status of a dialplan entry
IAX_COMMAND_DPREP = 20 # Request status of a dialplan entry
IAX_COMMAND_DIAL = 21 # Request a dial on channel brought up TBD
IAX_COMMAND_TXREQ = 22 # Transfer Request
IAX_COMMAND_TXCNT = 23 # Transfer Connect
IAX_COMMAND_TXACC = 24 # Transfer Accepted
IAX_COMMAND_TXREADY = 25 # Transfer ready
IAX_COMMAND_TXREL = 26 # Transfer release
IAX_COMMAND_TXREJ = 27 # Transfer reject
IAX_COMMAND_QUELCH = 28 # Stop audio/video transmission
IAX_COMMAND_UNQUELCH = 29 # Resume audio/video transmission
IAX_COMMAND_POKE = 30 # Like ping, but does not require an open connection
IAX_COMMAND_PAGE = 31 # Paging description
IAX_COMMAND_MWI = 32 # Stand-alone message waiting indicator
IAX_COMMAND_UNSUPPORT = 33 # Unsupported message received
IAX_COMMAND_TRANSFER = 34 # Request remote transfer
IAX_COMMAND_PROVISION = 35 # Provision device
IAX_COMMAND_FWDOWNL = 36 # Download firmware
IAX_COMMAND_FWDATA = 37 # Firmware Data
IAX_COMMAND_TXMEDIA = 38 # Transfer media only
IAX_COMMAND_CALLTOKEN = 40 # Call number token
IAX_DEFAULT_REG_EXPIRE = 60 # By default require re-registration once per minute
IAX_LINGER_TIMEOUT = 10 # How long to wait before closing bridged call
IAX_DEFAULT_PORTNO = 4569
IAX_IE_CALLED_NUMBER = 1 # Number/extension being called - string
IAX_IE_CALLING_NUMBER = 2 # Calling number - string
IAX_IE_CALLING_ANI = 3 # Calling number ANI for billing - string
IAX_IE_CALLING_NAME = 4 # Name of caller - string
IAX_IE_CALLED_CONTEXT = 5 # Context for number - string
IAX_IE_USERNAME = 6 # Username (peer or user) for authentication - string
IAX_IE_PASSWORD = 7 # Password for authentication - string
IAX_IE_CAPABILITY = 8 # Actual codec capability - unsigned int
IAX_IE_FORMAT = 9 # Desired codec format - unsigned int
IAX_IE_LANGUAGE = 10 # Desired language - string
IAX_IE_VERSION = 11 # Protocol version - short
IAX_IE_ADSICPE = 12 # CPE ADSI capability - short
IAX_IE_DNID = 13 # Originally dialed DNID - string
IAX_IE_AUTHMETHODS = 14 # Authentication method(s) - short
IAX_IE_CHALLENGE = 15 # Challenge data for MD5/RSA - string
IAX_IE_MD5_RESULT = 16 # MD5 challenge result - string
IAX_IE_RSA_RESULT = 17 # RSA challenge result - string
IAX_IE_APPARENT_ADDR = 18 # Apparent address of peer - struct sockaddr_in
IAX_IE_REFRESH = 19 # When to refresh registration - short
IAX_IE_DPSTATUS = 20 # Dialplan status - short
IAX_IE_CALLNO = 21 # Call number of peer - short
IAX_IE_CAUSE = 22 # Cause - string
IAX_IE_IAX_UNKNOWN = 23 # Unknown IAX command - byte
IAX_IE_MSGCOUNT = 24 # How many messages waiting - short
IAX_IE_AUTOANSWER = 25 # Request auto-answering -- none
IAX_IE_MUSICONHOLD = 26 # Request musiconhold with QUELCH -- none or string
IAX_IE_TRANSFERID = 27 # Transfer Request Identifier -- int
IAX_IE_RDNIS = 28 # Referring DNIS -- string
IAX_IE_PROVISIONING = 29 # Provisioning info
IAX_IE_AESPROVISIONING = 30 # AES Provisioning info
IAX_IE_DATETIME = 31 # Date/Time
IAX_IE_DEVICETYPE = 32 # Device Type -- string
IAX_IE_SERVICEIDENT = 33 # Service Identifier -- string
IAX_IE_FIRMWAREVER = 34 # Firmware revision -- u16
IAX_IE_FWBLOCKDESC = 35 # Firmware block description -- u32
IAX_IE_FWBLOCKDATA = 36 # Firmware block of data -- raw
IAX_IE_PROVVER = 37 # Provisioning Version (u32)
IAX_IE_CALLINGPRES = 38 # Calling presentation (u8)
IAX_IE_CALLINGTON = 39 # Calling type of number (u8)
IAX_IE_CALLINGTNS = 40 # Calling transit network select (u16)
IAX_IE_SAMPLINGRATE = 41 # Supported sampling rates (u16)
IAX_IE_CAUSECODE = 42 # Hangup cause (u8)
IAX_IE_ENCRYPTION = 43 # Encryption format (u16)
IAX_IE_ENCKEY = 44 # Encryption key (raw)
IAX_IE_CODEC_PREFS = 45 # Codec Negotiation
IAX_IE_RR_JITTER = 46 # Received jitter (as in RFC1889) u32
IAX_IE_RR_LOSS = 47 # Received loss (high byte loss pct, low 24 bits loss count, as in rfc1889
IAX_IE_RR_PKTS = 48 # Received frames (total frames received) u32
IAX_IE_RR_DELAY = 49 # Max playout delay for received frames (in ms) u16
IAX_IE_RR_DROPPED = 50 # Dropped frames (presumably by jitterbuf) u32
IAX_IE_RR_OOO = 51 # Frames received Out of Order u32
IAX_IE_CALLTOKEN = 54 # Call number security token
IAX_AUTH_PLAINTEXT = (1 << 0)
IAX_AUTH_MD5 = (1 << 1)
IAX_AUTH_RSA = (1 << 2)
IAX_ENCRYPT_AES128 = (1 << 0)
IAX_META_TRUNK = 1 # Trunk meta-message
IAX_META_VIDEO = 2 # Video frame
IAX_META_TRUNK_SUPERMINI = 0 # This trunk frame contains classic supermini frames
IAX_META_TRUNK_MINI = 1 # This trunk frame contains trunked mini frames
IAX_RATE_8KHZ = (1 << 0) # 8khz sampling (default if absent)
IAX_RATE_11KHZ = (1 << 1) # 11.025khz sampling
IAX_RATE_16KHZ = (1 << 2) # 16khz sampling
IAX_RATE_22KHZ = (1 << 3) # 22.05khz sampling
IAX_RATE_44KHZ = (1 << 4) # 44.1khz sampling
IAX_RATE_48KHZ = (1 << 5) # 48khz sampling
IAX_DPSTATUS_EXISTS = (1 << 0)
IAX_DPSTATUS_CANEXIST = (1 << 1)
IAX_DPSTATUS_NONEXISTENT = (1 << 2)
IAX_DPSTATUS_IGNOREPAT = (1 << 14)
IAX_DPSTATUS_MATCHMORE = (1 << 15)
IAX_FIRMWARE_MAGIC = 0x69617879
